server:
  #默认8761
  port: 10100
spring:
  application:
    name: eureka
eureka:
  instance:
    # 应用实例主机名
    hostname: localhost
    # true: 以IP地址注册到服务中心，相互注册使用IP地址
    #preferIpAddress: true
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    # 是否向注册中心注册自己 单节点自己不注册
    register-with-eureka: false
    # 是否从Eureka获取注册信息
    fetch-registry: false
    serviceUrl:
      #单节点暴露给注册者的注册地址， 多节点为另外eureka的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewal-percent-threshold: 0.49