server:
  port: 10102
spring:
  application:
    name: client
eureka:
  client:
    # 是否向注册中心注册自己
    register-with-eureka: false
    # 是否从Eureka获取注册信息
    serviceUrl:
      #单节点暴露给注册者的注册地址， 多节点为另外eureka的地址
      defaultZone: http://localhost:10100/eureka/