server:
  port: 10102
  #tomcat:
    #threads:
      #max: 10
spring:
  application:
    name: client
eureka:
  client:
    # 是否向注册中心注册自己
    register-with-eureka: false
    # 是否从Eureka获取注册信息
    serviceUrl:
      #单节点暴露给注册者的注册地址， 多节点为另外eureka的地址
      defaultZone: http://root:root@localhost:10100/eureka/
ribbon:
  ReadTimeout: 60000 #请求处理的超时时间
  ConnectTimeout: 60000 #请求连接的超时时间
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
